import { Roboto } from "next/font/google";
import "../styles/globals.css"

const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500', '700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main>
          {children}
          {/* {the shared ui components with all pages} */}
          
        </main>
        
      </body>
    </html>
  );
}
